spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.123.2.83:3306/Tencent_Trip?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: pool-vscloud
      connectionTestQuery: SELECT 1
      maximum-pool-size: 50
      minimum-idle: 10